### ISSUE TITLE
Config is shared across multiple charts

### ISSUE THREAD

**Issue by polandj** [AlbinoDrought/chartjs-plugin-watermark#1]
SUppose I have these charts:

var largestChart = new Chart($("#largestPieChart"), {
                        type: 'doughnut',
                        data: {
                            labels: _.map(largest, 0),
                            datasets: [{
                                data: _.map(largest, 2),
                                backgroundColor: colors
                            }]
                        },
                        options: {
                            watermark: {
                                image: "/assets/images/calyze.png",
                                alignX: "left",
                                alignY: "top",
                                position: "back",
                                opacity: 0.5
                            }
                        }
                    });
var longestChart = new Chart($("#longestPieChart"), {
                        type: 'doughnut',
                        data: {
                            labels: _.map(longest, 0),
                            datasets: [{
                                data: _.map(longest, 2),
                                backgroundColor: colors
                            }]
                        },
                        options: {
                            watermark: {
                                image: "/assets/images/calyze.png",
                                alignX: "middle",
                                alignY: "middle",
                                position: "front",
                                opacity: 1
                            }
                        }
                    });

Both watermarks will have the last options used: middle, front, 1.

**Comment by AlbinoDrought** [comment]
Fixed this. I thought Chart.helpers.extend cloned the initial object as well. Also added samples/multiple

**Comment by polandj** [comment]
Thanks!
