### ISSUE TITLE
Broken for Chart.js V3

### ISSUE THREAD

**Issue by austinonchain** [AlbinoDrought/chartjs-plugin-watermark#6]
This was written for version 2 of chart.js. It doesn't work for version 3, even after changing Chart.pluginService.register(watermarkPlugin); to Chart.register(watermarkPlugin);

**Comment by richardfat7** [comment]
You can try to patch `chartjs-plugin-watermark.js` by this:
```
39,40d38
<     
<     id: "watermark",
96c94
<             var context = chartInstance.ctx;
---
>             var context = chartInstance.chart.ctx;
160c158
<                 watermark = Object.assign(clonedDefaultOptions, options.watermark);
---
>                 watermark = helpers.extend(clonedDefaultOptions, options.watermark);
192c190
< Chart.register(watermarkPlugin);
---
> Chart.pluginService.register(watermarkPlugin);
```

**Comment by AlbinoDrought** [comment]
#7 has been merged (thanks @sschandi !) and is live at https://www.npmjs.com/package/chartjs-plugin-watermark/v/2.0.0
